# Generated by Django 3.0.3 on 2020-03-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200313_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password2',
        ),
        migrations.AddField(
            model_name='users',
            name='confpassword',
            field=models.CharField(default='123456789', max_length=100),
            preserve_default=False,
        ),
    ]
