# Generated by Django 3.0.3 on 2020-03-18 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_auto_20200318_1024'),
        ('users', '0005_newblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
