# Generated by Django 3.0.3 on 2020-03-14 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20200313_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='image',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 13, 21, 33, 59, 883652)),
        ),
    ]
