# Generated by Django 3.0.3 on 2020-03-24 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_auto_20200318_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='media/Desert.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 23, 17, 30, 33, 969123)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 23, 17, 30, 33, 969123)),
        ),
    ]
